#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

'''
In the following script we have first downloaded the chapter.txt. And after that
we have manipulated it to get files
'''


with open ('/Users/salendrapradh/Documents/Python_practise/Lessons/book_chapter.txt', 'r', encoding= 'utf-8' ) as file:
    for line in file:
        line = line.strip()
        if line:
            if len(line) > 50:
                print (line[0:50], '...')
            else:
                print (line[0:50])